config/routes.rb
Rails.application.routes.draw do
  devise_for :podcasts

  resources :podcasts , only: [:index, :show] do
    resources :episodes
  end

  authenticated :podcast do
    root 'podcasts#dashboard', as: "authenticated_root"
  end

  root 'welcome#index'

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :podcast

  has_attached_file :episode_thumbnail, :styles => { :large => '1000x1000#', :medium => '550x550#', :thumb => '100x100>' }
  validates_attachment_content_type :episode_thumbnail, :content_type => /\Aimage\/.*\Z/


  has_attached_file :mp3
  validates_attachment :mp3, :content_type => { :content_type => ['audio/mpeg', 'audio/mp3'] }, :file_name => { :matches =>[/mp3\Z/] }


end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :episodes

  has_attached_file :thumbnail, :styles => { :large => "1000x1000#", :medium => "550x550#", :thumb => "100x100>" }
  validates_attachment_content_type :thumbnail, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:title, :email, :password, :password_confirmation, :thumbnail)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:email, :password, :password_confirmation, :current_password, :title, :description, :itunes, :stitcher, :podbay, :thumbnail)}

  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :authenticate_podcast!, except: [:show]
  #before_filter :require_permission
  before_action :find_podcast
  before_action :find_episode, only: [:show, :edit, :update, :destroy]

  def new
    @episode = @podcast.episodes.new
  end

  def create
    @episode = @podcast.episodes.new(episode_params)
    if @episode.save
      redirect_to podcast_episode_path(@podcast, @episode)
    else
      render 'new'
    end
  end

  def show
    @episodes = Episode.where(podcast_id: @podcast).order("created_at DESC").limit(6).reject { |e| e.id == @episode.id }
  end

  def edit
  end

  def update
    if @episode.update episode_params
      redirect_to podcast_episode_path(@podcast, @episode), notice: "Episode was succesfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @episode.destroy
    redirect_to root_path
  end

  private

  def episode_params
    params.require(:episode).permit(:title, :description, :episode_thumbnail, :mp3)
  end

  def find_podcast
    @podcast = Podcast.find(params[:podcast_id])
  end

  def find_episode
    @episode = Episode.find(params[:id])
  end

=begin
  def require_permission
    @podcast = Podcast.find(params[:podcast_id])
    if current_podcast != @podcast
      redirect_to root_path, notice: "Sorry, you're not allowed to view that page"
    end
  end
=end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :find_podcast, only: [:show, :dashboard]
  before_action :find_episode, only: [:show, :dashboard]

  def index
    @podcasts = Podcast.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 12)
  end

  def show
  end

  def dashboard
  end

  private

  def find_episode
    @episodes = Episode.where(podcast_id: @podcast).order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end

  def find_podcast
    if params[:id].nil?
      @podcast = current_podcast
    else
      @podcast = Podcast.find(params[:id])
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/episodes/_form.html.erb
<%= form_for ([@podcast, @episode]) do |f| %>


    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>


    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>


    <div class="field">
      <%= f.label :episode_thumbnail %><br>
      <%= f.file_field :episode_thumbnail %>
    </div>


    <div class="field">
      <%= f.label :mp3 %><br>
      <%= f.file_field :mp3 %>
    </div>


    <%= f.submit class: "button button_highlight button_block" %>
<% end %>

app/views/episodes/edit.html.erb
<div id="podcast_show">
  <div id="show_banner">
    <div class="wrapper_skinny">
      <h1>The Rocketship Podcast Dashboard</h1>
    </div>
  </div>


  <div id="links">
    <div class="wrapper_skinny">
      <ul>
        <li><%= link_to "Episodes", root_path %></li>
        <li><%= link_to "New Episode", new_podcast_episode_path(@podcast) %></li>
        <li><%= link_to "Account Settings", edit_podcast_registration_path %></li>
        <li><%= link_to "View Podcast", podcast_path(current_podcast) %></li>
      </ul>
    </div>
  </div>


  <div id="form">
    <div class="wrapper_skinny">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/episodes/new.html.erb
<div id="podcast_show">
  <div id="show_banner">
    <div class="wrapper_skinny">
      <h1>The Rocketship Podcast Dashboard</h1>
    </div>
  </div>

  <div id="links">
    <div class="wrapper_skinny">
      <ul>
        <li><%= link_to "Episodes", root_path %></li>
        <li><%= link_to "New Episode", new_podcast_episode_path(@podcast), class: "current" %></li>
        <li><%= link_to "Account Settings", edit_podcast_registration_path %></li>
        <li><%= link_to "View Podcast", podcast_path(current_podcast) %></li>
      </ul>
    </div>
  </div>

  <div id="form">
    <div class="wrapper_skinny">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/episodes/show.html.erb
<div id="podcast_show">
  <div id="show_banner">
    <div class="wrapper_skinny">
      <h1><%= @podcast.title %></h1>
      <p class="description"><%= @podcast.description %></p>
      <% unless @podcast.itunes.blank? %>
          <a href='<%= @podcast.itunes %>' class='subscribe_link'>iTunes</a>
      <% end %>
      <% unless @podcast.stitcher.blank? %>
          <a href='<%= @podcast.stitcher %>' class='subscribe_link'>Stitcher</a>
      <% end %>

      <% unless @podcast.podbay.blank? %>
          <a href='<%= @podcast.podbay %>' class='subscribe_link'>PodBay</a>
      <% end %>
    </div>
  </div>

  <div id="breadcrumb">
    <%= link_to podcasts_path do%>
        All Podcasts
        <span>/</span>
        <%= link_to @podcast.title, podcast_path(@podcast) %>
        <span>/</span> <%= @episode.title %>
    <% end %>
  </div>

  <div id="episode_content">
    <div class="wrapper_skinny">
      <%= image_tag @episode.episode_thumbnail.url(:medium), class:'current_episode_thumbnail'%>
      <h2><%= @episode.title %></h2>
      <p class="description"><%= @episode.description %></p>

      <div id="jquery_jplayer_1" class="jp-jplayer"></div>
      <div id="jp_container_1" class="jp-audio">
        <div class="jp-type-single">
          <div class="jp-gui jp-interface">
            <ul class="jp-controls">
              <li><a href="javascript:;" class="jp-play" tabindex="1">&#61515;</a></li>
              <li><a href="javascript:;" class="jp-pause" tabindex="1">&#61516;</a></li>
              <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">&#61480;</a></li>
              <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">&#61478;</a></li>
            </ul>

            <div class="jp-progress">
              <div class="jp-seek-bar">
                <div class="jp-play-bar"></div>
              </div>
            </div>

            <div class="jp-time-holder">
              <div class="jp-current-time"></div>
            </div>

            <div class="jp-volume-bar">
              <div class="jp-volume-bar-value"></div>
            </div>

            <div class="jp-no-solution">
              <span>Update Required</span>
              To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>



  <div id="episodes">
    <div class="wrapper_skinny">
      <ul class="cf">
        <% @episodes.each do |episode| %>
            <li class="cf">
              <div class="episode_thumbnail">
                <a href="">
                  <%= image_tag episode.episode_thumbnail.url(:medium), class:'current_episode_thumbnail'%>
                </a>
              </div>
              <div class="episode_overview">
                <h2><%= link_to episode.title, podcast_episode_path(@podcast, episode)%></h2>
                <p class="description"><%= truncate(episode.description, length: 150)%></p>
              </div>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<script>
    $(document).ready(function(){
        $("#jquery_jplayer_1").jPlayer({
            ready: function () {
                $(this).jPlayer("setMedia", {
                    mp3: "<%= @episode.mp3.url %>"
                });
            },
            swfPath: "/js",
            supplied: "mp3"
        });
    });
</script>

app/views/layouts/_footer.html.erb
<div class="cf">
    <% @name = 'Adam Debbagh'%>
    <%= "Developed by #{@name}" %>
</div>

app/views/layouts/_header.html.erb
<header id="main_header" class="cf">
  <div class="wrapper_wide">

    <%= link_to 'UoPodcast', root_path, id:'logo' %>
    <nav>
      <ul>
        <% unless podcast_signed_in? %>
            <li><%= link_to 'Explore', podcasts_path %></li>
            <li><%= link_to 'Sign In', new_podcast_session_path %></li>
            <li><%= link_to 'Create a Podcast', new_podcast_registration_path %></li>
        <% else %>
            <li><%= link_to 'Explore', podcasts_path %></li>
            <li><%= link_to "Dashboard", edit_podcast_registration_path %></li>
            <li><%= link_to 'Sign Out', destroy_podcast_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UoPodcast</title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
<!--notifications-->



<% if notice %>
    <div id="notice_wrapper">
        <p class="notice"><%= notice %></p>
    </div>
    <% elsif alert %>
    <div id="notice_wrapper">
        <p class="alert"><%= alert %></p>
    </div>
<% end %>

<% unless current_page?(root_path) %>
    <%= render 'layouts/header'%>
<% end %>

<%= yield %>
<%= render 'layouts/footer'%>

<script>
    $(document).ready(function(){
        setTimeout(function() {
            $('#notice_wrapper').fadeOut("slow", function() {
                $this.remove();
            });
        }, 2500 );
    });
</script>

</body>
</html>

app/views/podcasts/dashboard.html.erb
<%= render 'layouts/header'%>
<div id="podcast_show">
  <div id="show_banner">
    <div class="wrapper_skinny">
      <h1>The Podcast <%= @podcast.title %> Dashboard</h1>
    </div>
  </div>

  <div id="links">
    <div class="wrapper_skinny">
      <ul>
        <li class="current">Episodes</li>
        <li><%= link_to "New Episode", new_podcast_episode_path(@podcast) %></li>
        <li><%= link_to "Account Settings", edit_podcast_registration_path %></li>
        <li><%= link_to "View Podcast", podcast_path(current_podcast) %></li>
      </ul>
    </div>
  </div>

  <div id="episodes">
    <div class="wrapper_skinny">
      <ul class="cf">
        <% @episodes.each do |episode| %>
            <li class="cf">
              <div class="episode_thumbnail">
                <a href="episode.html">
                  <%= image_tag episode.episode_thumbnail.url(:medium) %>
                </a>
              </div>
              <div class="episode_overview">
                <h2><%= link_to episode.title, podcast_episode_path(@podcast, episode) %></h2>
                <p class="description"><%= truncate(episode.description, lenght: 160) %></p>
                <div class="authorized_links">
                  <%= link_to "Edit", edit_podcast_episode_path(@podcast, episode) %>
                  <%= link_to "Delete", podcast_episode_path(@podcast, episode), method: :delete, data: {confirm: "Are you sure?"} %>
                </div>
              </div>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<%= will_paginate @episodes, previous_label: "Previous", next_label: "Next" %>

app/views/podcasts/index.html.erb
<div id="banner" class="podcasts_banner">
  <h1>Discover your new favorite podcast</h1>
</div>

<div id="podcasts" class="cf">
  <div class="wrapper">
    <ul class="cf">
      <% @podcasts.each do |podcast| %>
          <%= link_to podcast do %>
              <li>
                <%= image_tag podcast.thumbnail.url(:medium) %>
                <div class="podcast_overview">
                  <h2><%= podcast.title %></h2>
                  <p class="episode_count">1 Episode</p>
                </div>
              </li>
          <% end %>
      <% end %>
    </ul>

    <%= will_paginate @podcasts, previous_label: "Previous", next_label: "Next" %>
  </div>
</div>

app/views/podcasts/show.html.erb
<div id="podcast_show">
  <div id="show_banner">
    <div class="wrapper_skinny">
      <h1><%= @podcast.title %></h1>
      <p class="description"><%= @podcast.description %></p>
      <% unless @podcast.itunes.blank? %>
          <a href='<%= @podcast.itunes %>' class='subscribe_link'>iTunes</a>
      <% end %>
      <% unless @podcast.stitcher.blank? %>
        <a href='<%= @podcast.stitcher %>' class='subscribe_link'>Stitcher</a>
      <% end %>

      <% unless @podcast.podbay.blank? %>
        <a href='<%= @podcast.podbay %>' class='subscribe_link'>PodBay</a>
      <% end %>
    </div>
  </div>

  <div id="breadcrumb">
    <%= link_to podcasts_path do %>
        All Podcasts
        <span>/</span>
        The Rocketship Podcast
        <% end %>
  </div>

  <div id="episodes">
    <div class="wrapper_skinny">
      <ul class="cf">
        <% @episodes.each do |episode|%>
            <li class="cf">
              <div class="episode_thumbnail">
                <a href="#">
                  <%= image_tag episode.episode_thumbnail.url(:medium) %>
                </a>
              </div>
              <div class="episode_overview">
                <h2><%= link_to episode.title, podcast_episode_path(@podcast, episode) %></h2>
                <p class="description"><%= truncate(episode.description, length: 150)%></p>
              </div>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<%= will_paginate @episodes, previous_label: "Previous", next_label: "Next" %>

app/views/welcome/index.html.erb
<main>
<div id="background">

  <header class="cf">
    <div class="wrapper_wide">
      <div class="section group">
        <div class="col span_1_of_2">
            <a href="index.html" id="logo">UoPodcast</a>
        </div>
        <div class="col span_1_of_2">
          <nav>
            <ul>
              <% unless podcast_signed_in? %>
                  <li><%= link_to 'Explore', podcasts_path %></li>
                  <li><%= link_to 'Sign In', new_podcast_session_path %></li>
                  <li><%= link_to 'Create a Podcast', new_podcast_registration_path %></li>
              <% else %>
                  <li><%= link_to 'Explore', podcasts_path %></li>
                  <li><a href="#">Dashboard</a></li>
                  <li><%= link_to 'Sign Out', destroy_podcast_session_path, method: :delete %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </header>
  <div class="wrapper_skinny">
    <%= link_to 'Create a Podcast', new_podcast_registration_path, class: 'button button_highlight' %>
    <%= link_to 'Explore', podcasts_path, class:'button button_white' %>
  </div>
  </div>

</main>